# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1215, 774)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.saveListBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveListBtn.setObjectName("saveListBtn")
        self.gridLayout_14.addWidget(self.saveListBtn, 0, 0, 1, 1)
        self.delItemBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delItemBtn.setObjectName("delItemBtn")
        self.gridLayout_14.addWidget(self.delItemBtn, 0, 2, 1, 1)
        self.loadListBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loadListBtn.setObjectName("loadListBtn")
        self.gridLayout_14.addWidget(self.loadListBtn, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_14)
        self.dataList = QtWidgets.QListWidget(self.centralwidget)
        self.dataList.setMinimumSize(QtCore.QSize(300, 0))
        self.dataList.setMaximumSize(QtCore.QSize(300, 16777215))
        self.dataList.setDragEnabled(False)
        self.dataList.setObjectName("dataList")
        self.verticalLayout_2.addWidget(self.dataList)
        self.openFileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openFileBtn.setMinimumSize(QtCore.QSize(300, 30))
        self.openFileBtn.setMaximumSize(QtCore.QSize(300, 50))
        self.openFileBtn.setObjectName("openFileBtn")
        self.verticalLayout_2.addWidget(self.openFileBtn)
        self.plotBtn = QtWidgets.QPushButton(self.centralwidget)
        self.plotBtn.setMinimumSize(QtCore.QSize(300, 30))
        self.plotBtn.setMaximumSize(QtCore.QSize(300, 50))
        self.plotBtn.setObjectName("plotBtn")
        self.verticalLayout_2.addWidget(self.plotBtn)
        self.fftBtn = QtWidgets.QPushButton(self.centralwidget)
        self.fftBtn.setMinimumSize(QtCore.QSize(300, 30))
        self.fftBtn.setMaximumSize(QtCore.QSize(300, 50))
        self.fftBtn.setObjectName("fftBtn")
        self.verticalLayout_2.addWidget(self.fftBtn)
        self.clearFileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearFileBtn.setMinimumSize(QtCore.QSize(300, 30))
        self.clearFileBtn.setMaximumSize(QtCore.QSize(300, 50))
        self.clearFileBtn.setObjectName("clearFileBtn")
        self.verticalLayout_2.addWidget(self.clearFileBtn)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 7, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(330, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(330, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.echoRadio = QtWidgets.QRadioButton(self.groupBox)
        self.echoRadio.setObjectName("echoRadio")
        self.gridLayout_2.addWidget(self.echoRadio, 0, 0, 1, 1)
        self.usrRadio = QtWidgets.QRadioButton(self.groupBox)
        self.usrRadio.setObjectName("usrRadio")
        self.gridLayout_2.addWidget(self.usrRadio, 0, 1, 1, 1)
        self.usrRadio.raise_()
        self.echoRadio.raise_()
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(330, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(330, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fitCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.fitCheckBox.setObjectName("fitCheckBox")
        self.gridLayout_3.addWidget(self.fitCheckBox, 0, 0, 1, 1)
        self.besselFitRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.besselFitRadio.setObjectName("besselFitRadio")
        self.gridLayout_3.addWidget(self.besselFitRadio, 1, 0, 1, 1)
        self.PLLFitRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.PLLFitRadio.setObjectName("PLLFitRadio")
        self.gridLayout_3.addWidget(self.PLLFitRadio, 1, 1, 1, 1)
        self.perpFitRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.perpFitRadio.setObjectName("perpFitRadio")
        self.gridLayout_3.addWidget(self.perpFitRadio, 1, 2, 1, 1)
        self.yOffEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.yOffEdit.setObjectName("yOffEdit")
        self.gridLayout_3.addWidget(self.yOffEdit, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 0, 1, 1, 1)
        self.PLLFitRadio.raise_()
        self.fitCheckBox.raise_()
        self.besselFitRadio.raise_()
        self.perpFitRadio.raise_()
        self.yOffEdit.raise_()
        self.label_24.raise_()
        self.verticalLayout.addWidget(self.groupBox_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(330, 0))
        self.widget.setMaximumSize(QtCore.QSize(330, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.smRadio = QtWidgets.QRadioButton(self.widget)
        self.smRadio.setText("")
        self.smRadio.setObjectName("smRadio")
        self.gridLayout_7.addWidget(self.smRadio, 1, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.widget)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 2, 4, 1, 1)
        self.cRadio = QtWidgets.QRadioButton(self.widget)
        self.cRadio.setText("")
        self.cRadio.setObjectName("cRadio")
        self.gridLayout_7.addWidget(self.cRadio, 2, 0, 1, 1)
        self.coarsenlevelSpinBox = QtWidgets.QSpinBox(self.widget)
        self.coarsenlevelSpinBox.setProperty("value", 2)
        self.coarsenlevelSpinBox.setObjectName("coarsenlevelSpinBox")
        self.gridLayout_7.addWidget(self.coarsenlevelSpinBox, 2, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 1, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.widget)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 1, 4, 1, 1)
        self.smthPolSpinBox = QtWidgets.QSpinBox(self.widget)
        self.smthPolSpinBox.setProperty("value", 2)
        self.smthPolSpinBox.setObjectName("smthPolSpinBox")
        self.gridLayout_7.addWidget(self.smthPolSpinBox, 1, 5, 1, 1)
        self.isCoarsenBox = QtWidgets.QCheckBox(self.widget)
        self.isCoarsenBox.setObjectName("isCoarsenBox")
        self.gridLayout_7.addWidget(self.isCoarsenBox, 2, 1, 1, 1)
        self.smthLengthSpinBox = QtWidgets.QSpinBox(self.widget)
        self.smthLengthSpinBox.setProperty("value", 11)
        self.smthLengthSpinBox.setObjectName("smthLengthSpinBox")
        self.gridLayout_7.addWidget(self.smthLengthSpinBox, 1, 3, 1, 1)
        self.smoothingCheckBox = QtWidgets.QCheckBox(self.widget)
        self.smoothingCheckBox.setObjectName("smoothingCheckBox")
        self.gridLayout_7.addWidget(self.smoothingCheckBox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(330, 0))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(330, 16777215))
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 318, 524))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.paramTab = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.paramTab.setMinimumSize(QtCore.QSize(300, 300))
        self.paramTab.setMaximumSize(QtCore.QSize(300, 300))
        self.paramTab.setObjectName("paramTab")
        self.echoTab = QtWidgets.QWidget()
        self.echoTab.setObjectName("echoTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.echoTab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.echoParamPhiMinEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamPhiMinEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamPhiMinEdit.setObjectName("echoParamPhiMinEdit")
        self.gridLayout_10.addWidget(self.echoParamPhiMinEdit, 9, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.echoTab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_10.addWidget(self.label_10, 6, 0, 1, 1)
        self.echoParamT2StartEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamT2StartEdit.setObjectName("echoParamT2StartEdit")
        self.gridLayout_10.addWidget(self.echoParamT2StartEdit, 3, 2, 1, 1)
        self.echoParamAMaxEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamAMaxEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamAMaxEdit.setObjectName("echoParamAMaxEdit")
        self.gridLayout_10.addWidget(self.echoParamAMaxEdit, 2, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.echoTab)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_10.addWidget(self.label_17, 0, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.echoTab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.echoTab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 3, 0, 1, 1)
        self.gParaFixCheckBox = QtWidgets.QCheckBox(self.echoTab)
        self.gParaFixCheckBox.setText("")
        self.gParaFixCheckBox.setObjectName("gParaFixCheckBox")
        self.gridLayout_10.addWidget(self.gParaFixCheckBox, 7, 1, 1, 1)
        self.echoParamAResultEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamAResultEdit.setEnabled(True)
        self.echoParamAResultEdit.setObjectName("echoParamAResultEdit")
        self.gridLayout_10.addWidget(self.echoParamAResultEdit, 2, 5, 1, 1)
        self.fmFixCheckBox = QtWidgets.QCheckBox(self.echoTab)
        self.fmFixCheckBox.setText("")
        self.fmFixCheckBox.setObjectName("fmFixCheckBox")
        self.gridLayout_10.addWidget(self.fmFixCheckBox, 6, 1, 1, 1)
        self.echoParamNMinEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamNMinEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamNMinEdit.setObjectName("echoParamNMinEdit")
        self.gridLayout_10.addWidget(self.echoParamNMinEdit, 4, 3, 1, 1)
        self.echoParamCResultEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamCResultEdit.setEnabled(True)
        self.echoParamCResultEdit.setObjectName("echoParamCResultEdit")
        self.gridLayout_10.addWidget(self.echoParamCResultEdit, 5, 5, 1, 1)
        self.echoParamNStartEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamNStartEdit.setObjectName("echoParamNStartEdit")
        self.gridLayout_10.addWidget(self.echoParamNStartEdit, 4, 2, 1, 1)
        self.echoParamFmStartEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamFmStartEdit.setObjectName("echoParamFmStartEdit")
        self.gridLayout_10.addWidget(self.echoParamFmStartEdit, 6, 2, 1, 1)
        self.echoParamNMaxEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamNMaxEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamNMaxEdit.setObjectName("echoParamNMaxEdit")
        self.gridLayout_10.addWidget(self.echoParamNMaxEdit, 4, 4, 1, 1)
        self.phiFixCheckBox = QtWidgets.QCheckBox(self.echoTab)
        self.phiFixCheckBox.setText("")
        self.phiFixCheckBox.setObjectName("phiFixCheckBox")
        self.gridLayout_10.addWidget(self.phiFixCheckBox, 9, 1, 1, 1)
        self.echoParamT2MaxEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamT2MaxEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamT2MaxEdit.setObjectName("echoParamT2MaxEdit")
        self.gridLayout_10.addWidget(self.echoParamT2MaxEdit, 3, 4, 1, 1)
        self.echoParamT2MinEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamT2MinEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamT2MinEdit.setObjectName("echoParamT2MinEdit")
        self.gridLayout_10.addWidget(self.echoParamT2MinEdit, 3, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.echoTab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_10.addWidget(self.label_20, 4, 0, 1, 1)
        self.echoParamFmResultEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamFmResultEdit.setEnabled(True)
        self.echoParamFmResultEdit.setObjectName("echoParamFmResultEdit")
        self.gridLayout_10.addWidget(self.echoParamFmResultEdit, 6, 5, 1, 1)
        self.echoParamFmMinEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamFmMinEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamFmMinEdit.setObjectName("echoParamFmMinEdit")
        self.gridLayout_10.addWidget(self.echoParamFmMinEdit, 6, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.echoTab)
        self.label_15.setMinimumSize(QtCore.QSize(0, 20))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.echoTab)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.echoTab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_10.addWidget(self.label_7, 5, 0, 1, 1)
        self.echoParamCMaxEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamCMaxEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamCMaxEdit.setObjectName("echoParamCMaxEdit")
        self.gridLayout_10.addWidget(self.echoParamCMaxEdit, 5, 4, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.echoTab)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_10.addWidget(self.label_25, 0, 5, 1, 1)
        self.echoParamT2ResultEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamT2ResultEdit.setEnabled(True)
        self.echoParamT2ResultEdit.setObjectName("echoParamT2ResultEdit")
        self.gridLayout_10.addWidget(self.echoParamT2ResultEdit, 3, 5, 1, 1)
        self.echoParamAStartEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamAStartEdit.setObjectName("echoParamAStartEdit")
        self.gridLayout_10.addWidget(self.echoParamAStartEdit, 2, 2, 1, 1)
        self.echoParamGammaBzStartEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamGammaBzStartEdit.setObjectName("echoParamGammaBzStartEdit")
        self.gridLayout_10.addWidget(self.echoParamGammaBzStartEdit, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.echoTab)
        self.label_21.setObjectName("label_21")
        self.gridLayout_10.addWidget(self.label_21, 1, 0, 1, 1)
        self.echoParamAMinEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamAMinEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamAMinEdit.setObjectName("echoParamAMinEdit")
        self.gridLayout_10.addWidget(self.echoParamAMinEdit, 2, 3, 1, 1)
        self.echoParamCMinEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamCMinEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamCMinEdit.setObjectName("echoParamCMinEdit")
        self.gridLayout_10.addWidget(self.echoParamCMinEdit, 5, 3, 1, 1)
        self.echoParamNResultEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamNResultEdit.setEnabled(True)
        self.echoParamNResultEdit.setObjectName("echoParamNResultEdit")
        self.gridLayout_10.addWidget(self.echoParamNResultEdit, 4, 5, 1, 1)
        self.echoParamCStartEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamCStartEdit.setObjectName("echoParamCStartEdit")
        self.gridLayout_10.addWidget(self.echoParamCStartEdit, 5, 2, 1, 1)
        self.echoParamPhiResultEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamPhiResultEdit.setEnabled(True)
        self.echoParamPhiResultEdit.setObjectName("echoParamPhiResultEdit")
        self.gridLayout_10.addWidget(self.echoParamPhiResultEdit, 9, 5, 1, 1)
        self.echoParamGparaMaxEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamGparaMaxEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamGparaMaxEdit.setObjectName("echoParamGparaMaxEdit")
        self.gridLayout_10.addWidget(self.echoParamGparaMaxEdit, 7, 4, 1, 1)
        self.gPerpFixCheckBox = QtWidgets.QCheckBox(self.echoTab)
        self.gPerpFixCheckBox.setText("")
        self.gPerpFixCheckBox.setObjectName("gPerpFixCheckBox")
        self.gridLayout_10.addWidget(self.gPerpFixCheckBox, 8, 1, 1, 1)
        self.echoParamGperpStartEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamGperpStartEdit.setObjectName("echoParamGperpStartEdit")
        self.gridLayout_10.addWidget(self.echoParamGperpStartEdit, 8, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.echoTab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 8, 0, 1, 1)
        self.echoParamPhiStartEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamPhiStartEdit.setObjectName("echoParamPhiStartEdit")
        self.gridLayout_10.addWidget(self.echoParamPhiStartEdit, 9, 2, 1, 1)
        self.echoParamGperpResultEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamGperpResultEdit.setEnabled(True)
        self.echoParamGperpResultEdit.setObjectName("echoParamGperpResultEdit")
        self.gridLayout_10.addWidget(self.echoParamGperpResultEdit, 8, 5, 1, 1)
        self.echoParamGperpMaxEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamGperpMaxEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamGperpMaxEdit.setObjectName("echoParamGperpMaxEdit")
        self.gridLayout_10.addWidget(self.echoParamGperpMaxEdit, 8, 4, 1, 1)
        self.echoParamGparaResultEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamGparaResultEdit.setEnabled(True)
        self.echoParamGparaResultEdit.setObjectName("echoParamGparaResultEdit")
        self.gridLayout_10.addWidget(self.echoParamGparaResultEdit, 7, 5, 1, 1)
        self.echoParamFmMaxEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamFmMaxEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamFmMaxEdit.setObjectName("echoParamFmMaxEdit")
        self.gridLayout_10.addWidget(self.echoParamFmMaxEdit, 6, 4, 1, 1)
        self.echoParamGperpMinEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamGperpMinEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamGperpMinEdit.setObjectName("echoParamGperpMinEdit")
        self.gridLayout_10.addWidget(self.echoParamGperpMinEdit, 8, 3, 1, 1)
        self.echoParamPhiMaxEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamPhiMaxEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamPhiMaxEdit.setObjectName("echoParamPhiMaxEdit")
        self.gridLayout_10.addWidget(self.echoParamPhiMaxEdit, 9, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.echoTab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 7, 0, 1, 1)
        self.echoParamGparaMinEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamGparaMinEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.echoParamGparaMinEdit.setObjectName("echoParamGparaMinEdit")
        self.gridLayout_10.addWidget(self.echoParamGparaMinEdit, 7, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.echoTab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 9, 0, 1, 1)
        self.echoParamGparaStartEdit = QtWidgets.QLineEdit(self.echoTab)
        self.echoParamGparaStartEdit.setObjectName("echoParamGparaStartEdit")
        self.gridLayout_10.addWidget(self.echoParamGparaStartEdit, 7, 2, 1, 1)
        self.cFixCheckBox = QtWidgets.QCheckBox(self.echoTab)
        self.cFixCheckBox.setText("")
        self.cFixCheckBox.setObjectName("cFixCheckBox")
        self.gridLayout_10.addWidget(self.cFixCheckBox, 5, 1, 1, 1)
        self.aFixCheckBox = QtWidgets.QCheckBox(self.echoTab)
        self.aFixCheckBox.setText("")
        self.aFixCheckBox.setObjectName("aFixCheckBox")
        self.gridLayout_10.addWidget(self.aFixCheckBox, 2, 1, 1, 1)
        self.nFixCheckBox = QtWidgets.QCheckBox(self.echoTab)
        self.nFixCheckBox.setText("")
        self.nFixCheckBox.setObjectName("nFixCheckBox")
        self.gridLayout_10.addWidget(self.nFixCheckBox, 4, 1, 1, 1)
        self.t2FixCheckBox = QtWidgets.QCheckBox(self.echoTab)
        self.t2FixCheckBox.setText("")
        self.t2FixCheckBox.setObjectName("t2FixCheckBox")
        self.gridLayout_10.addWidget(self.t2FixCheckBox, 3, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.echoTab)
        self.label_22.setObjectName("label_22")
        self.gridLayout_10.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.echoTab)
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 1, 4, 1, 1)
        self.bzEdit = QtWidgets.QLineEdit(self.echoTab)
        self.bzEdit.setText("")
        self.bzEdit.setObjectName("bzEdit")
        self.gridLayout_10.addWidget(self.bzEdit, 1, 5, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_10)
        self.paramTab.addTab(self.echoTab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 5, 2, 1, 1)
        self.mrkSizeEdit = QtWidgets.QLineEdit(self.tab_3)
        self.mrkSizeEdit.setObjectName("mrkSizeEdit")
        self.gridLayout_5.addWidget(self.mrkSizeEdit, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 5, 0, 1, 1)
        self.lgndCheckBox = QtWidgets.QCheckBox(self.tab_3)
        self.lgndCheckBox.setChecked(True)
        self.lgndCheckBox.setObjectName("lgndCheckBox")
        self.gridLayout_5.addWidget(self.lgndCheckBox, 0, 1, 1, 1)
        self.lineSizeEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineSizeEdit.setObjectName("lineSizeEdit")
        self.gridLayout_5.addWidget(self.lineSizeEdit, 3, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 2, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 4, 0, 1, 1)
        self.textSizeEdit = QtWidgets.QLineEdit(self.tab_3)
        self.textSizeEdit.setObjectName("textSizeEdit")
        self.gridLayout_5.addWidget(self.textSizeEdit, 4, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_5.addWidget(self.lineEdit_4, 5, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_3)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 1, 0, 1, 1)
        self.lgndLocEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lgndLocEdit.setObjectName("lgndLocEdit")
        self.gridLayout_5.addWidget(self.lgndLocEdit, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.paramTab.addTab(self.tab_3, "")
        self.verticalLayout_4.addWidget(self.paramTab)
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser.setMinimumSize(QtCore.QSize(300, 200))
        self.textBrowser.setMaximumSize(QtCore.QSize(300, 600))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.gridLayout.addLayout(self.verticalLayout, 2, 5, 1, 1)
        self.mplwindow = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setMinimumSize(QtCore.QSize(100, 100))
        self.mplwindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mplwindow.setObjectName("mplwindow")
        self.mplvlMain = QtWidgets.QVBoxLayout(self.mplwindow)
        self.mplvlMain.setContentsMargins(0, 0, 0, 0)
        self.mplvlMain.setObjectName("mplvlMain")
        self.gridLayout.addWidget(self.mplwindow, 0, 0, 7, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1215, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.paramTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saveListBtn.setText(_translate("MainWindow", "Save list"))
        self.delItemBtn.setText(_translate("MainWindow", "Delete from list"))
        self.loadListBtn.setText(_translate("MainWindow", "Load list"))
        self.openFileBtn.setText(_translate("MainWindow", "Open files"))
        self.plotBtn.setText(_translate("MainWindow", "Plot"))
        self.fftBtn.setText(_translate("MainWindow", "FFT"))
        self.clearFileBtn.setText(_translate("MainWindow", "Clear files"))
        self.groupBox.setTitle(_translate("MainWindow", "Plot target"))
        self.echoRadio.setText(_translate("MainWindow", "Echo"))
        self.usrRadio.setText(_translate("MainWindow", "Custom Plot"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Fitting"))
        self.fitCheckBox.setText(_translate("MainWindow", "Fitting"))
        self.besselFitRadio.setText(_translate("MainWindow", "Bessel Fitting"))
        self.PLLFitRadio.setText(_translate("MainWindow", "PLL Fitting"))
        self.perpFitRadio.setText(_translate("MainWindow", "Perp Fitting"))
        self.yOffEdit.setText(_translate("MainWindow", "-0.12"))
        self.label_24.setText(_translate("MainWindow", "y offset"))
        self.label_33.setText(_translate("MainWindow", "CoarsenLevel"))
        self.label_13.setText(_translate("MainWindow", "Deg."))
        self.label_32.setText(_translate("MainWindow", "Pol."))
        self.isCoarsenBox.setText(_translate("MainWindow", "Coarsen"))
        self.smoothingCheckBox.setText(_translate("MainWindow", "Smoothing"))
        self.echoParamPhiMinEdit.setText(_translate("MainWindow", "-180"))
        self.label_10.setText(_translate("MainWindow", "fm [kHz]"))
        self.echoParamT2StartEdit.setText(_translate("MainWindow", "7.2"))
        self.echoParamAMaxEdit.setText(_translate("MainWindow", "100"))
        self.label_17.setText(_translate("MainWindow", "Max."))
        self.label_19.setText(_translate("MainWindow", "a"))
        self.label_18.setText(_translate("MainWindow", "T2 [us]"))
        self.echoParamNMinEdit.setText(_translate("MainWindow", "0"))
        self.echoParamNStartEdit.setText(_translate("MainWindow", "2"))
        self.echoParamFmStartEdit.setText(_translate("MainWindow", "650"))
        self.echoParamNMaxEdit.setText(_translate("MainWindow", "3"))
        self.echoParamT2MaxEdit.setText(_translate("MainWindow", "100"))
        self.echoParamT2MinEdit.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "n"))
        self.echoParamFmMinEdit.setText(_translate("MainWindow", "550"))
        self.label_15.setText(_translate("MainWindow", "Value"))
        self.label_16.setText(_translate("MainWindow", "Min."))
        self.label_7.setText(_translate("MainWindow", "c"))
        self.echoParamCMaxEdit.setText(_translate("MainWindow", "2"))
        self.label_25.setText(_translate("MainWindow", "Result"))
        self.echoParamAStartEdit.setText(_translate("MainWindow", "0.033"))
        self.echoParamGammaBzStartEdit.setText(_translate("MainWindow", "30"))
        self.label_21.setText(_translate("MainWindow", "rBz[MHz]"))
        self.echoParamAMinEdit.setText(_translate("MainWindow", "0"))
        self.echoParamCMinEdit.setText(_translate("MainWindow", "0"))
        self.echoParamCStartEdit.setText(_translate("MainWindow", "0.9"))
        self.echoParamGparaMaxEdit.setText(_translate("MainWindow", "0.5"))
        self.echoParamGperpStartEdit.setText(_translate("MainWindow", "0.1"))
        self.label_14.setText(_translate("MainWindow", "Gperp [MHz]"))
        self.echoParamPhiStartEdit.setText(_translate("MainWindow", "0"))
        self.echoParamGperpMaxEdit.setText(_translate("MainWindow", "0.5"))
        self.echoParamFmMaxEdit.setText(_translate("MainWindow", "750"))
        self.echoParamGperpMinEdit.setText(_translate("MainWindow", "0"))
        self.echoParamPhiMaxEdit.setText(_translate("MainWindow", "180"))
        self.label_11.setText(_translate("MainWindow", "Gpara [MHz]"))
        self.echoParamGparaMinEdit.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "phi [Deg]"))
        self.echoParamGparaStartEdit.setText(_translate("MainWindow", "0.1"))
        self.label_22.setText(_translate("MainWindow", "Fix"))
        self.label_23.setText(_translate("MainWindow", "Bz[G]"))
        self.paramTab.setTabText(self.paramTab.indexOf(self.echoTab), _translate("MainWindow", "Echo"))
        self.pushButton.setText(_translate("MainWindow", "Explore.."))
        self.mrkSizeEdit.setText(_translate("MainWindow", "8"))
        self.label_9.setText(_translate("MainWindow", "Path"))
        self.lgndCheckBox.setText(_translate("MainWindow", "Legend"))
        self.lineSizeEdit.setText(_translate("MainWindow", "3"))
        self.label_34.setText(_translate("MainWindow", "MarkerSize"))
        self.label_35.setText(_translate("MainWindow", "LineSize"))
        self.label_8.setText(_translate("MainWindow", "TextSize"))
        self.textSizeEdit.setText(_translate("MainWindow", "15"))
        self.label_36.setText(_translate("MainWindow", "LegendLoc"))
        self.lgndLocEdit.setText(_translate("MainWindow", "2"))
        self.paramTab.setTabText(self.paramTab.indexOf(self.tab_3), _translate("MainWindow", "Save Img."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

